### ISSUE TITLE
Dados do comprador no Checkout PagSeguro

### ISSUE THREAD

**Issue by rfperuch** [CarlosWGama/php-pagseguro#12]
Notei que ao utilizar o Checkout PagSeguro, informar o email e nome do comprador não faz diferença na página de checkout do PagSeguro.

```php
$pagseguro->setNomeCliente("CARLOS W GAMA");
$pagseguro->setEmailCliente("c73062863531198591643@sandbox.pagseguro.com.br");
```

Eu esperaria que informando ambos os dados ao carregar a página de checkout, a conta do comprador já fosse 'pré-selecionada', bastando apenas informar a senha. Mas não é o que acontece.

Poderiam por favor me esclarecer se isto está correto?

**Comment by CarlosWGama** [comment]
Olá Rodrigo. O principal papel dela é para o checkout transparente, o qual o programador não acessar o pagseguro, faz tudo pelo seu site.

**Comment by rfperuch** [comment]
Oi @CarlosWGama obrigado pelo feedback. Vou deixar sem isso mesmo. Abraços.
