### ISSUE TITLE
Roubo de dados

### ISSUE THREAD

**Issue by restd01** [CarlosWGama/php-pagseguro#16]
Ontem registrei um boletim de ocorrência de uma fraude no meu cartão de credito, foi feito várias compras com o seu nome como estabelecimento. A instituição bancária colaborou me passando os dados das transações indevidas, como local, cnpj, e o tipo da transação.
Todos sabemos que você é programador renomado e tem conhecimento avançado em API's e compras online, mas agora vai ter que prestar esclarecimentos para policia por esses crimes.

**Comment by CarlosWGama** [comment]
Todos os códigos daqui  da API são códigos abertos, ou seja, não tem nem como eu roubar dados de ninguém.  Todo mundo que conheça um pouco de programação consegue ver isso.

Assim como eu não tenho estabelecimento algum.

Então se alguém que acabou de criar uma conta no github e está seguindo só o meu repositório com uma fake, está tentando dá um golpe em mim, só lamento. Não vai consegui :)

EDIT: Não irei apagar essa issue, só para ficar como prova que não tenho nada a temer dos meus códigos
