### ISSUE TITLE
Me Ajude

### ISSUE THREAD

**Issue by thallysbr** [CarlosWGama/php-pagseguro#4]
Como faço para neste modo do pagseguro desativar a opção de endereço na página de pagamento ?

Já tentei de tudo, e diferentes bibliotecas e não consigo em nenhuma.
Meus produtos são virtuais logo, não tem porque eu pedir o endereço ao cliente, nem meio de entrega.

Agradeço se puder me ajudar, desculpe o incomodo.

**Comment by CarlosWGama** [comment]
O campo endereço ele é obrigatório para o PagSeguro, por isso que você sempre o encontra. 

Mas caso deseje que o usuário não informe o endereço, basta você não pedir ao usuário essa informação. E na hora de fazer a compra, usa um endereço fictício ou genérico.

**Comment by thallysbr** [comment]
é que vi outros sites vendendo produto virtual, eles não pedem o endereço na compra e nem opção de entrega.

**Comment by CarlosWGama** [comment]
Se eles usam o PagSeguro por trás, na hora de informar o endereço eles devem usar o da própria empresa, por exemplo, uma vez que é um campo solicitado como obrigatório pelo PagSeguro.
