### ISSUE TITLE
Cancelamento de plano gerando erro.

### ISSUE THREAD

**Issue by eliseusbcom** [CarlosWGama/php-pagseguro#5]
Olá, pode me ajudar se possível?

No cancelamento da assinatura, um erro é retornado.

"pre-approval not found."

Consta que o código da assinatura não é um PreApproval, mas está cadastrada na lista e ativa.

include_once dirname(dirname(__FILE__)).'/_gateway/vendor/autoload.php';
use CWG\PagSeguro\PagSeguroAssinaturas;

$token = $dp['token_pagseguro'];
$email = $dp['email_pagseguro'];
$sandbox = $dp['sandbox_pagseguro'];
$pagseguro = new PagSeguroAssinaturas($email, $token, $sandbox);
$codePagSeguro = $dr['codigo']; // 2BDA5A58CECEBAB664497F85D7194DA6

try {
	print_r($pagseguro->cancelarAssinatura($codePagSeguro));
} catch (Exception $e) {
	echo $e->getMessage();
}

**Comment by CarlosWGama** [comment]
Opa @eliseusbcom 

Verifica se de fato você está pegando o código da assinatura e não do plano.

Também pode checar se  esse código ai ele pertence de fato ao mesmo ambiente (sandbox ou produção) do que está tentando cancelar.

**Comment by eliseusbcom** [comment]
oi, consegui, de fato era o código, obrigado, seu código é mais competente que o da própria pagseguro, obrigado mesmo por isso.

**Comment by CarlosWGama** [comment]
Valeu. Qualquer coisa é só perguntar ;)
