### ISSUE TITLE
Adição do Código do erro no retorno

### ISSUE THREAD

**Issue by gio-dev** [CarlosWGama/php-pagseguro#6]
Poderia adicionar o código de erro no retorno para que seja possível efetuar o tratamento dos erros na parte de assinatura? Fiz a modificação manualmente mas poderia ser útil para outras pessoas.

Arquivo: PagSeguroAssinaturas.php (classe), função assinaPlano,  Linha 294 (pode ser usado em qualquer retorno de erro)

		//Dados do cliente
		$dados['sender'] 		= $this->cliente;
		//Dados do pagamento
		$dados['paymentMethod'] = $this->formaPagamento;
		//Dados do plano
		$dados['plan'] 			= $this->planoCode;
		//Dados da compra
		$dados['reference']		= $this->referencia;

		$response = $this->post($this->getURLAPI('pre-approvals/'), $dados);

		if ($response['http_code'] == 200) {
			return $response['body']['code'];
		} else {
			throw new \Exception(current($response['body']['errors']), key($response['body']['errors']));
		}

**Comment by CarlosWGama** [comment]
Adicionado e dado os devidos créditos ^^

Na próxima, caso deseje pode enviar como um pull request, para ficar com a sua conta vinculada como autor da alteração ;)
