### ISSUE TITLE
consultarCompraByReferencia está com problemas

### ISSUE THREAD

**Issue by luccasr73** [CarlosWGama/php-pagseguro#8]
Indirect modification of overloaded element of SimpleXMLElement has no effect in C:\wamp64\www\losgrandes\vendor\carloswgama\php-pagseguro\src\PagSeguroCompras.php on line 539

**Comment by CarlosWGama** [comment]
Poderia passar mais informação Luccas? para eu ver o que pode ser o problema

**Comment by luccasr73** [comment]
Então só testei no modo produção, não sei dizer quanto ao sandbox, mas quando consulto uma compra pela referencia da um erro no parse do xml.

São dois warnings:
Warning: It is not yet possible to assign complex types to attributes in C:\wamp64\www\losgrandes\vendor\carloswgama\php-pagseguro\src\PagSeguroCompras.php on line 538
Notice: Indirect modification of overloaded element of SimpleXMLElement has no effect in C:\wamp64\www\losgrandes\vendor\carloswgama\php-pagseguro\src\PagSeguroCompras.php on line 539

Versão do meu php: 7.1

**Comment by CarlosWGama** [comment]
Acredito que o PagSeguro deve estar retornando um código diferente. Por via das duvidas, você tem certeza que está usando um código de referência valido e que pertença a conta vinculada nas credenciais? (Lembrando que as compras do Sandbox não existem em Produção e vice-versa)

**Comment by luccasr73** [comment]
Certeza, estou usando as credenciais corretas nos ambientes corretos

**Comment by CarlosWGama** [comment]
Infelizmente só consigo identificar o problema se tiver acesso ao código :/

Caso deseje, pode mandar para meu email carloswgama@gmail.com

**Comment by luccasr73** [comment]
eu só peguei o codigo daqui https://github.com/CarlosWGama/php-pagseguro/blob/master/examples/compra/consulta.php, troquei as credenciais pelas minhas e deixei só a parte de código de Referencia

**Comment by CarlosWGama** [comment]
No caso a referência é a "$referencia = 'CWG004';"? Foi realizado alguma compra com suas credências usando essa referência antes?

Do contrário, de fato a referência é inválida para suas credenciais.

**Comment by luccasr73** [comment]
Foi uma referencia valida sim, alterei ela para uma referencia valida minha

**Comment by luccasr73** [comment]
Acho que acabei não explicando direito, o resultado esperado acontece e é retornado o array com a transação, mas aparecem os warning mencionados acima na tela

**Comment by CarlosWGama** [comment]
Testei aqui com os meus dados e o código está funcionando normalmente. Qual a sua versão do PHP?

**Comment by CarlosWGama** [comment]
Uma alternativa também é desabilitar os warnings, caso ele esteja pegando normalmente.

**Comment by luccasr73** [comment]
php 7.1

**Comment by CarlosWGama** [comment]
Caso esteja usando a ultima versão da biblioteca (3.x), ela não deveria dar problema com o PHP 7.1. 

Nesse caso só tendo acesso aos dados para fazer um debug mesmo. Mas caso não queria, pode desejar o warning usando o código abaixo no inicio do seu script:
`error_reporting(E_ALL ^ E_WARNING);`
