### ISSUE TITLE
LightBox não abre no mobile

### ISSUE THREAD

**Issue by luccasr73** [CarlosWGama/php-pagseguro#9]
O LightBox não abre em plataformas mobile

**Comment by CarlosWGama** [comment]
Essa biblioteca utiliza o próprio javascript disponibilizado pelo PagSeguro. 

A questão é que lightbox disponibilizada pelo PagSeguro não funciona em mobile por não ser auto responsivo. 

Uma sugestão que eu dou é usar algum código que verifique se o usuário está usando mobile. Caso esteja, use o checkout padrão ao invés do lightbox.
